app = 'gdrivegenie-app'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    NEXT_PUBLIC_API_URL = 'https://gdrivegenie-api.fly.dev'

[[services]]
  internal_port = 3000
  protocol      = 'tcp'
  auto_stop_machines  = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers    = ['http']
    port        = 80
    force_https = true

  [[services.ports]]
    handlers = ['tls', 'http']
    port     = 443
