app = 'gdrivegenie-api'
primary_region = 'iad'

[build]
  dockerfile = 'backend/Dockerfile'

[env]
  CONFIG_DIR = '/app/config'

[[services]]
  internal_port = 8000
  protocol      = 'tcp'
  auto_stop_machines  = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers    = ['http']
    port        = 80
    force_https = true

  [[services.ports]]
    handlers = ['tls', 'http']
    port     = 443

  [services.concurrency]
    type       = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval       = 10000
    timeout        = 2000
    grace_period   = "5s"
    method         = "get"
    path           = "/active"
    protocol       = "http"
    restart_limit  = 0

[[mounts]]
  source       = 'gdrivegenie_config'
  destination  = '/app/config'
  initial_size = '1gb'
